Added SSH key support
crossplane-contrib/provider-terraform pull request #77
Opened 2022-07-19 09:03 UTC by vglafirov

### Adds ssh keys support 
* Added ssh keys support to connector object
* Creating controller user within image, this is required for ssh
* Adding some logging and debugging messages

-->
Fixes #30

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Tested creating resources using ssh based URL for module and transitive dependencies. 

[contribution process]: https://git.io/fj2m9

2022-07-19 10:13 UTC, ytsarev requested changes

2022-07-19 10:13 UTC, ytsarev commented on README.md
> +- The provider won't emit an event until _after_ it has successfully applied the
I think it appeared in the last iteration of this PR as well, there is no reason to modify markdown to some different style which is apparently specific to your IDE :)

2022-07-19 10:25 UTC, ytsarev commented
@bobh66 this PR should also fix #54 , thanks to writeable $HOME creation. Do you want to give it a shot for your scenario before the merge?

2022-08-30 21:35 UTC, ytsarev commented
@vglafirov do you still want to work on this change?

2022-09-16 08:06 UTC, luisdavim commented
any updates on this?

2022-09-16 11:25 UTC, ytsarev commented
We just agreed with @vglafirov that me and/or @bobh66 will takeover this PR soon and will try to incorporate it into the next release.

2023-06-06 19:32 UTC, davidwincent commented
> any updates on this?

+1 checking the status of this

github seems to have dropped support for password authentication 2021?

```bash
❯ git config --global credential.helper store
❯ git clone https://github.com/***/argocd-apps.git
Cloning into 'argocd-apps'...
Username for 'https://github.com': ***
Password for 'https://***@github.com':
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/***/argocd-apps.git/'
```

See https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls

2024-01-12 04:46 UTC, soony88 commented
Would really like this feature to move through, this PR has been sitting here for too long :(

Our organisation enforces SSH authentication so this is a critical feature for us

2024-01-20 16:21 UTC, closed without merging